import CoreGraphics
import Foundation
import Testing
@testable import OtterCore

/// Counts how often a pasteboard flag is read.
private final class FlagProbe {
    var reads = 0
    let value: Bool

    init(_ value: Bool) {
        self.value = value
    }

    func read() -> Bool {
        reads += 1
        return value
    }
}

// MARK: - Private pasteboards

@Test(arguments: [
    (["org.nspasteboard.ConcealedType", "public.utf8-plain-text"], true),
    (["org.nspasteboard.TransientType", "public.utf8-plain-text"], true),
    (["public.utf8-plain-text", "org.nspasteboard.TransientType", "org.nspasteboard.ConcealedType"], true),
    (["public.utf8-plain-text"], false),
    (["org.nspasteboard.AutoGeneratedType", "public.utf8-plain-text"], false),
    ([], false),
])
func privatePasteboardsAreRecognisedByTheirTypes(types: [String], expected: Bool) {
    #expect(PasteRules.isPrivate(types: types) == expected)
}

@Test(arguments: ["org.nspasteboard.ConcealedType", "org.nspasteboard.TransientType"])
func aPrivateClipboardIsSkippedWithoutReadingIt(marker: String) {
    let hasText = FlagProbe(true)
    let hasFileURLs = FlagProbe(true)

    let content = ClipboardRules.content(types: [marker, "public.utf8-plain-text", "public.png"], hasFileURLs: hasFileURLs.read(), hasText: hasText.read())

    #expect(content == .private)
    #expect(hasText.reads == 0)
    #expect(hasFileURLs.reads == 0)
}

// MARK: - What the clipboard holds

@Test(arguments: [
    // A ⌃⇧⌘4 screenshot.
    (["public.png"], false, false, ClipboardContent.image(uti: "public.png")),
    (["public.png", "public.tiff"], false, false, .image(uti: "public.png")),
    // Files copied in Finder come with their names as text and an icon: the files win.
    (["public.file-url", "public.utf8-plain-text", "public.tiff"], true, true, .files),
    // Text from a web page.
    (["public.html", "public.rtf", "public.utf8-plain-text"], false, true, .text),
    // Text from Word or Pages, with a picture of it.
    (["public.rtf", "public.utf8-plain-text", "public.png"], false, true, .text),
    // A browser's "Copy Image".
    (["public.html", "public.png"], false, false, .image(uti: "public.png")),
    // A URL from the address bar is plain text.
    (["public.url", "public.utf8-plain-text"], false, true, .text),
    (["public.utf8-plain-text"], false, true, .text),
    // Only whitespace, nothing at all, or only formatted text with no plain text.
    (["public.utf8-plain-text"], false, false, .empty),
    ([], false, false, .empty),
    (["public.rtf"], false, false, .empty),
    // Image types Otter doesn't attach.
    (["com.compuserve.gif"], false, false, .empty),
])
func clipboardContent(types: [String], hasFileURLs: Bool, hasText: Bool, expected: ClipboardContent) {
    #expect(ClipboardRules.content(types: types, hasFileURLs: hasFileURLs, hasText: hasText) == expected)
}

// MARK: - HUD messages

@Test(arguments: [
    (ClipboardSaveOutcome.saved(destinationName: "Otter Inbox", skippedFiles: 0), "Saved to Otter Inbox", true),
    (.saved(destinationName: "Vault", skippedFiles: 1), "Saved to Vault · 1 file skipped", true),
    (.saved(destinationName: "Vault", skippedFiles: 3), "Saved to Vault · 3 files skipped", true),
    (.alreadySaved, "Already saved", true),
    (.empty, "Clipboard is empty", false),
    (.skippedPrivate, "Skipped — copied from a password manager", false),
    (.noDestination, "Not saved — no destination set up", false),
    (.outOfSpace, "Not saved — disk is full", false),
    (.outboxFailed, "Not saved — couldn't write to Otter's outbox", false),
    (.notAttached(.tooLarge(name: "talk.mov")), "“talk.mov” is over 200 MB, so it can't be attached.", false),
    (.notAttached(.folder(name: "Photos")), "“Photos” is a folder. Only files can be attached.", false),
    (.attachmentsUnsupported(destinationName: "Apple Notes"), "Not saved — Apple Notes can't take attachments", false),
])
func hudMessages(outcome: ClipboardSaveOutcome, message: String, isSuccess: Bool) {
    #expect(outcome.message == message)
    #expect(outcome.isSuccess == isSuccess)
}

@Test func aFullDiskIsToldApartFromOtherOutboxFailures() {
    #expect(ClipboardSaveOutcome.notSaved(CocoaError(.fileWriteOutOfSpace)) == .outOfSpace)
    #expect(ClipboardSaveOutcome.notSaved(NSError(domain: NSPOSIXErrorDomain, code: Int(ENOSPC))) == .outOfSpace)
    #expect(ClipboardSaveOutcome.notSaved(CocoaError(.fileWriteNoPermission)) == .outboxFailed)
}

// MARK: - Already saved

@Test func theSameClipboardWithinTenSecondsIsAlreadySaved() {
    var dedup = ClipboardDedup()
    #expect(dedup.begin(changeCount: 7, now: 100) == .save)
    dedup.finish(changeCount: 7, saved: true, at: 100.5)

    #expect(dedup.begin(changeCount: 7, now: 101) == .alreadySaved)
    #expect(dedup.begin(changeCount: 7, now: 110.4) == .alreadySaved)
}

@Test func theWindowCountsFromTheSaveAndIsNotExtendedByRepeats() {
    var dedup = ClipboardDedup()
    _ = dedup.begin(changeCount: 7, now: 100)
    dedup.finish(changeCount: 7, saved: true, at: 100)
    #expect(dedup.begin(changeCount: 7, now: 105) == .alreadySaved)

    #expect(dedup.begin(changeCount: 7, now: 110) == .save)
}

@Test func aNewCopyIsSaved() {
    var dedup = ClipboardDedup()
    _ = dedup.begin(changeCount: 7, now: 100)
    dedup.finish(changeCount: 7, saved: true, at: 100)

    #expect(dedup.begin(changeCount: 8, now: 101) == .save)
}

@Test func aFailedSaveCanBeTriedAgain() {
    var dedup = ClipboardDedup()
    _ = dedup.begin(changeCount: 7, now: 100)
    dedup.finish(changeCount: 7, saved: false, at: 100)

    #expect(dedup.begin(changeCount: 7, now: 101) == .save)
}

@Test func aSecondPressWhileSavingIsIgnored() {
    var dedup = ClipboardDedup()
    #expect(dedup.begin(changeCount: 7, now: 100) == .save)
    #expect(dedup.begin(changeCount: 7, now: 100.2) == .inProgress)
    // Another copy meanwhile is saved on its own.
    #expect(dedup.begin(changeCount: 8, now: 100.3) == .save)

    dedup.finish(changeCount: 7, saved: true, at: 102)
    #expect(dedup.begin(changeCount: 7, now: 102.1) == .alreadySaved)
}

// MARK: - HUD placement

@Test func theHUDIsCentredAboveTheBottomOfTheVisibleFrame() {
    let visible = CGRect(x: 0, y: 80, width: 1512, height: 870)
    let frame = HUDPlacement.frame(contentWidth: 220.4, in: visible)

    #expect(frame.size == CGSize(width: 221, height: HUDPlacement.height))
    #expect(frame.minY == 80 + HUDPlacement.bottomOffset)
    #expect(abs(frame.midX - visible.midX) <= 0.5)
}

@Test func theHUDFollowsAScreenWithAnOffsetOrigin() {
    let visible = CGRect(x: 1512, y: -200, width: 2560, height: 1415)
    let frame = HUDPlacement.frame(contentWidth: 300, in: visible)

    #expect(frame.minX == CGFloat(1512 + (2560 - 300) / 2))
    #expect(frame.minY == -200 + HUDPlacement.bottomOffset)
}

@Test func aLongMessageIsKeptInsideTheMargins() {
    let visible = CGRect(x: 0, y: 0, width: 400, height: 600)
    let frame = HUDPlacement.frame(contentWidth: 900, in: visible)

    #expect(frame.minX == HUDPlacement.sideMargin)
    #expect(frame.maxX == 400 - HUDPlacement.sideMargin)
}

@Test func aShortVisibleFrameStillHoldsTheHUD() {
    let visible = CGRect(x: 0, y: 0, width: 800, height: 90)
    let frame = HUDPlacement.frame(contentWidth: 200, in: visible)

    #expect(frame.minY >= visible.minY)
    #expect(frame.maxY <= visible.maxY)
}
